#
#    Author by @Weesli
#

options:
  prefix: "&6Claim &8>> "
  # System showing the claim zone for players
  # 'Particle' and 'Border' are available.
  viewer-mode: particle
  # Storage type can be 'YAML' or 'MySQL'
  storage-type: YAML
  # The maximum number of people a beneficiary can trust.
  max-trusted-player: 10
  # Economy type can be 'VAULT' or 'none' or 'PLAYER_POINTS'
  economy-type: VAULT
  # sended location to all player when Exploded claim from any causes
  # if you don't want this setting, you change enabled to false
  claim-timeout-message:
    enabled: true
    text:
      - "&aThe claim region of &b%player% at coordinates &b%x% &b%z% has been destroyed!"
  # Worlds where Claim receipt is open
  active-worlds:
    - world
  enter-message:
    enabled: true
    # The format of the text that will appear when the player enters the region.
    # The format types are 'actionbar', 'title' and 'bossbar'.
    # To add a subtitle for title, you can add <> between two sentences. example. You have entered the territory of %player% <> Be careful
    format: "bossbar"
    text: "&cClaim owner &f%player%"
  time-format: "%week%w %day%d %hour%h %minute%m %second%s"
  # If you set the storage-type to 'MySQL' it will automatically use this one!
  database:
    host: localhost
    port: 3306
    username: root
    password: ""
    database: rclaims
  # Hologram usage (Optional)
  hologram:
    enabled: false
    # RClaim offers 1 options for holograms and which one you choose is entirely up to you.
    # Options = 'DecentHologram'
    # Only the person with the claim can see it
    hologram-module: DecentHologram
    hologram-settings:
      hologram-lines:
        - "&eBase Claim"
        - "&8"
        - "&aOwner : &f%player%"
        - "&a"
        - "&eRemaining time : %rclaim_<id>_time%"

claim-settings:
  # if change this setting of 0, claim is be free
  claim-cost: 10000
  # claim duration in days
  claim-duration: 30
  default-claim-status:
    SPAWN_ANIMAL: true
    SPAWN_MONSTER: false
    EXPLOSION: false
    PVP: false